name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ main ]

env:
  PROJECT_NAME: project_cicd
  BUCKET_NAME: store-reservation
  CODE_DEPLOY_APP_NAME: store-reservation
  DEPLOYMENT_GROUP_NAME: app-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # application.yml 파일 생성
      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources 
          cd ./src/main/resources
          touch application.yml
          
          echo "${{ secrets.APPLICAION_YML }}" >> application.yml
        shell: bash

      # - name: Setup MySQL
      #   uses: mirromutth/mysql-action@v1.1
      #   with:
      #     mysql database: 'reservation' 
      #     mysql user: ${{ secrets.MYSQL_USERNAME }}
      #     mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # Gradle build (Test 제외)
      - name: Build with Gradle
        run: ./gradlew clean --stacktrace --info build
        shell: bash

      # - name: Build with Gradle
      #   run: ./gradlew build
      #   shell: bash

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
        
